# Generated by Django 3.2.13 on 2022-07-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='id',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospitalCode',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
