version: '3'

services:
  redis:
    container_name: assict_redis
    image: redis:alpine
    ports:
    - "6379:6379"
  backend:
    container_name: assict_backend
    build:
      context: backend/assiCT_api_server
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=host.docker.internal
      - REDIS_SERVER=redis
    depends_on:
      - redis
  frontend:
    container_name: assict_frontend
    build:
      context: frontend/assict_front
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SOCKET_HOST=ws://localhost:8000/ws/alarm/
      - REACT_APP_API_HOST=http://backend:8000/
    command: npm run start
    depends_on:
      - backend
volumes:
  static:
    driver: local
  db_data:
    driver: local