global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
    monitor: 'assict-monitor'

rule_files:
  - "/prometheus/alert.rules"

scrape_configs:
  - job_name: assict_django
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets:
        - backend:8000

  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

