# Generated by Django 3.2.13 on 2022-07-09 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_imgUrl', models.CharField(max_length=128)),
                ('lime_imgUrl', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PatientResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('patientName', models.CharField(blank=True, max_length=10)),
                ('studyDate', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('total_dcm', models.IntegerField(default=0)),
                ('complete_dcm', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CtResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.BooleanField()),
                ('ct_img', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ct_result', to='ct.ctimage')),
                ('patient_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_results', to='ct.patientresult')),
            ],
        ),
    ]
