# Generated by Django 3.2.13 on 2022-06-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('patiendName', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CtResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.BooleanField()),
                ('imgDescription', models.CharField(max_length=256)),
                ('patient_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ct.patientresult')),
            ],
        ),
    ]
