# Generated by Django 3.2.13 on 2022-07-02 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientresult',
            old_name='patiendName',
            new_name='patientName',
        ),
        migrations.RemoveField(
            model_name='ctresult',
            name='imgDescription',
        ),
        migrations.AddField(
            model_name='patientresult',
            name='studyDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
