# Generated by Django 3.2.13 on 2022-07-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0002_auto_20220703_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.CharField(max_length=128)),
                ('ct_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ct.ctresult')),
            ],
        ),
        migrations.CreateModel(
            name='LimeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.CharField(max_length=128)),
                ('ct_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ct.ctresult')),
            ],
        ),
    ]
