# Generated by Django 3.2.13 on 2022-07-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0002_auto_20220713_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctresult',
            name='fileName',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
