# Generated by Django 3.2.13 on 2022-07-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0005_alter_ctresult_patient_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limeimage',
            name='ct_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lime_img', to='ct.ctresult'),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='ct_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original_img', to='ct.ctresult'),
        ),
    ]
