# Generated by Django 3.2.13 on 2022-07-04 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0007_auto_20220704_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_imgUrl', models.CharField(max_length=128)),
                ('lime_imgUrl', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='ctresult',
            name='lime_img',
        ),
        migrations.RemoveField(
            model_name='ctresult',
            name='original_img',
        ),
        migrations.DeleteModel(
            name='LimeImage',
        ),
        migrations.DeleteModel(
            name='OriginalImage',
        ),
        migrations.AddField(
            model_name='ctresult',
            name='ct_img',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ct_result', to='ct.ctimage'),
        ),
    ]
