# Generated by Django 3.2.13 on 2022-07-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0008_auto_20220704_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientresult',
            name='complete_dcm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientresult',
            name='total_dcm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientresult',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='patientresult',
            name='patientName',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
